insert into customers (first_name, last_name, city) values ('Gale', 'Lafaye', 'Międzybrodzie Bialskie');
insert into customers (first_name, last_name, city) values ('Ferd', 'Galway', 'Ani-e');
insert into customers (first_name, last_name, city) values ('Trudy', 'Murfett', 'Sayán');
insert into customers (first_name, last_name, city) values ('Crysta', 'Goranov', 'Novoselë');
insert into customers (first_name, last_name, city) values ('Mick', 'Terrazzo', 'Tranca');
insert into customers (first_name, last_name, city) values ('Corrine', 'Giacovazzo', 'Horana South');
insert into customers (first_name, last_name, city) values ('Susana', 'Scawton', 'Zebrzydowice');
insert into customers (first_name, last_name, city) values ('Diane-marie', 'Nason', 'Jincun');
insert into customers (first_name, last_name, city) values ('Shalom', 'De Gregoli', 'Luoluopu');
insert into customers (first_name, last_name, city) values ('Hadlee', 'Crumb', 'Abuyog');
insert into customers (first_name, last_name, city) values ('Laraine', 'Tutt', 'Duobagou');
insert into customers (first_name, last_name, city) values ('Michel', 'Abramof', 'Breda');
insert into customers (first_name, last_name, city) values ('Pru', 'Jeffress', 'Shihui');
insert into customers (first_name, last_name, city) values ('Dael', 'Dunkley', 'Mozhga');
insert into customers (first_name, last_name, city) values ('Kali', 'Merriman', 'Cotabambas');
insert into customers (first_name, last_name, city) values ('Marlee', 'Jerrome', 'Columbus');
insert into customers (first_name, last_name, city) values ('Scotti', 'Bunten', 'Zheleznogorsk-Ilimskiy');
insert into customers (first_name, last_name, city) values ('Monika', 'Biasioli', 'Ciroyom');
insert into customers (first_name, last_name, city) values ('Natal', 'Boram', 'Paya Dapur');
insert into customers (first_name, last_name, city) values ('Ginni', 'MacAnespie', 'Zhireken');
insert into customers (first_name, last_name, city) values ('Tiffie', 'Kenwin', 'Shiyuan');
insert into customers (first_name, last_name, city) values ('Rice', 'Kemwal', 'Beitou');
insert into customers (first_name, last_name, city) values ('Marlow', 'Younie', 'Simbal');
insert into customers (first_name, last_name, city) values ('Gan', 'Milier', 'Lucas');
insert into customers (first_name, last_name, city) values ('Giorgia', 'Cobbold', 'Melikkrajan');
insert into customers (first_name, last_name, city) values ('Robbin', 'Le feuvre', 'Nanhu');
insert into customers (first_name, last_name, city) values ('Saunderson', 'Vinten', 'Bouabout');
insert into customers (first_name, last_name, city) values ('Shepard', 'Patriskson', 'Budënnovsk');
insert into customers (first_name, last_name, city) values ('Natale', 'Heake', 'Las Matas de Santa Cruz');
insert into customers (first_name, last_name, city) values ('Haslett', 'Lyttle', 'Ţawr al Bāḩah');
insert into customers (first_name, last_name, city) values ('Beau', 'Dailly', 'Huayuan');
insert into customers (first_name, last_name, city) values ('Elle', 'Kermon', 'Boskovice');
insert into customers (first_name, last_name, city) values ('Allie', 'Pyer', 'Baghdad');
insert into customers (first_name, last_name, city) values ('Nevile', 'Bollum', 'Saraza');
insert into customers (first_name, last_name, city) values ('Max', 'Keese', 'N’dalatando');
insert into customers (first_name, last_name, city) values ('Karleen', 'Curreen', 'Papeete');
insert into customers (first_name, last_name, city) values ('Evelina', 'Stanlike', 'Baoluan');
insert into customers (first_name, last_name, city) values ('Donnie', 'Oxherd', 'Phak Hai');
insert into customers (first_name, last_name, city) values ('Earlie', 'Francey', 'Skrzyszów');
insert into customers (first_name, last_name, city) values ('Claudio', 'Dutch', 'Bangluo');
insert into customers (first_name, last_name, city) values ('Devinne', 'Siehard', 'Lewo');
insert into customers (first_name, last_name, city) values ('Verena', 'Buddleigh', 'Svetogorsk');
insert into customers (first_name, last_name, city) values ('Vinson', 'Garside', 'Sanhe');
insert into customers (first_name, last_name, city) values ('Malachi', 'Brundall', 'Nicola Town');
insert into customers (first_name, last_name, city) values ('Dill', 'Waggett', 'Loureiro');
insert into customers (first_name, last_name, city) values ('Sashenka', 'Coot', 'Miyoshi');
insert into customers (first_name, last_name, city) values ('Susana', 'Hacker', 'Rokytnice');
insert into customers (first_name, last_name, city) values ('Nettie', 'Abelov', 'Neftobod');
insert into customers (first_name, last_name, city) values ('Clarabelle', 'Robe', 'Aimorés');
insert into customers (first_name, last_name, city) values ('Maryjo', 'MacDonnell', 'Gazojak');