insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Jimmy', 'GMC', 1993, 1993);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Jimmy', 'GMC', 2001, 2001);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Grand Am', 'Pontiac', 1995, 1995);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('1500 Club Coupe', 'GMC', 1998, 1998);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Prizm', 'Chevrolet', 2002, 2002);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Sienna', 'Toyota', 2004, 2005);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('LR2', 'Land Rover', 2012, 2013);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Armada', 'Nissan', 2007, 2008);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('MDX', 'Acura', 2003, 2003);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Ram Van 2500', 'Dodge', 2003, 2004);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Silhouette', 'Oldsmobile', 1996, 1996);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('7 Series', 'BMW', 2007, 2008);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('62', 'Maybach', 2006, 2006);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('GTO', 'Mitsubishi', 1994, 1994);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Safari', 'Pontiac', 1987, 1987);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('GTO', 'Pontiac', 1973, 1974);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Galant', 'Mitsubishi', 1989, 1989);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Solara', 'Toyota', 2006, 2006);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Outlook', 'Saturn', 2009, 2010);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Malibu', 'Chevrolet', 1998, 1998);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Altima', 'Nissan', 2004, 2005);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Altima', 'Nissan', 2011, 2011);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Gallardo', 'Lamborghini', 2007, 2007);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Ram 2500', 'Dodge', 2008, 2009);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('940', 'Volvo', 1995, 1995);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('FJ Cruiser', 'Toyota', 2009, 2009);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Corvette', 'Chevrolet', 1961, 1962);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Grand Prix', 'Pontiac', 1991, 1991);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Premier', 'Eagle', 1992, 1993);
insert into vehicles (model_name, assembler, manufacture_year, model_year) values ('Aura', 'Saturn', 2008, 2008);